SELECT * FROM ITEMS WHERE WEIGHT = (SELECT MIN(WEIGHT) FROM ITEMS);

SELECT * FROM WAREHOUSES WHERE LOCATION = 'Pune';

SELECT ITEMS.* 
FROM ITEMS 
JOIN ORDER_ITEMS ON ITEMS.ITEMNO = ORDER_ITEMS.ITEMNO 
JOIN ORDERS ON ORDER_ITEMS.ONO = ORDERS.ONO 
JOIN CUSTOMER ON ORDERS.CNO = CUSTOMER.CNO 
WHERE CUSTOMER.CNAME = 'Mr. Patil';

SELECT WID, COUNT(*) AS NUM_STORES 
FROM STORES 
GROUP BY WID 
ORDER BY NUM_STORES DESC 
LIMIT 1;

SELECT ITEMS.*, SUM(ORDERED_QUANTITY) AS TOTAL_QUANTITY 
FROM ITEMS 
JOIN ORDER_ITEMS ON ITEMS.ITEMNO = ORDER_ITEMS.ITEMNO 
GROUP BY ITEMS.ITEMNO 
ORDER BY TOTAL_QUANTITY ASC 
LIMIT 1;

SELECT CUSTOMER.*, ORDERS.*, ITEMS.*, ORDER_ITEMS.ORDERED_QUANTITY 
FROM CUSTOMER 
JOIN ORDERS ON CUSTOMER.CNO = ORDERS.CNO 
JOIN ORDER_ITEMS ON ORDERS.ONO = ORDER_ITEMS.ONO 
JOIN ITEMS ON ORDER_ITEMS.ITEMNO = ITEMS.ITEMNO;
